
---
author: |
  | William Findlay
title: |
  | COMP3203 Final Exam Summary
date: \today
bibliography: /home/housedhorse/.bibs/uni.bib
csl: /home/housedhorse/.bibs/ieee.csl
subparagraph: yes
header-includes: |
  ``` {=latex}
  \usepackage{float}
  \usepackage{listings}
  \usepackage[hang,bf]{caption}
  \usepackage{framed}
  \usepackage[section]{placeins}

  \allowdisplaybreaks

  % fancy headers/footers
  \makeatletter
  \usepackage{fancyhdr}
  \lhead{\@author}
  \chead{}
  \rhead{\@title}
  \lfoot{}
  \cfoot{\thepage}
  \rfoot{}
  \renewcommand{\headrulewidth}{0.4pt}

  \usepackage{amsmath, amsfonts,amssymb, amsthm}
  \usepackage{siunitx}
  \usepackage[boxruled,lined,linesnumbered,titlenumbered]{algorithm2e}

  \usepackage{setspace}
  \usepackage{changepage}
  \usepackage[explicit]{titlesec}
  \usepackage{aliascnt}

  \floatplacement{figure}{!htb}
  \floatplacement{table}{!htb}
  \lstset{mathescape=true,numbers=left,breaklines=true,frame=single,language=python}
  \setlength{\captionmargin}{1in}

  \newgeometry{margin=1in}

  \newtheoremstyle{plain}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\itshape}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{definition}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{remark}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\itshape} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \theoremstyle{plain}

  % define theorem
  \newtheorem{theorem}{Theorem}[section]
  \providecommand*{\theoremautorefname}{Theorem}

  % define lemma
  \newtheorem{lemma}{Lemma}[section]
  \providecommand*{\lemmaautorefname}{Lemma}

  % define claim
  \newtheorem{claim}{Claim}[section]
  \providecommand*{\claimautorefname}{Claim}

  % define corollary
  \newtheorem{corollary}{Corollary}[section]
  \providecommand*{\corollaryautorefname}{Corollary}

  % define proposition
  \newtheorem{proposition}{Proposition}[section]
  \providecommand*{\propositionautorefname}{Proposition}

  % define conjecture
  \newtheorem{conjecture}{Conjecture}[section]
  \providecommand*{\conjectureautorefname}{Conjecture}

  \theoremstyle{remark}

  % define observation
  \newtheorem{observation}{Observation}[section]
  \providecommand*{\observationautorefname}{Observation}

  % define remark
  \newtheorem{remark}{Remark}[section]
  \providecommand*{\remarkautorefname}{Remark}

  \theoremstyle{definition}

  % define example
  \newtheorem{example}{Example}[section]
  \providecommand*{\exampleautorefname}{Example}

  % define definition
  \newtheorem{definition}{Definition}[section]
  \providecommand*{\definitionautorefname}{Definition}

  \newcommand{\blackbox}{\hfill$\blacksquare$}
  \usepackage{tikz}
  \newcommand*\circled[1]{\tikz[baseline=(char.base)]{
              \node[shape=circle,draw,inner sep=2pt] (char) {#1};}}

  \renewcommand{\labelitemi}{$\bullet$}
  \renewcommand{\labelitemiii}{\textbullet}
  \renewcommand{\labelitemiv}{-}

  \titleformat{\paragraph}
  {\itshape}
  {}
  {0em}
  {\underline{#1}}[ ]
  \titleformat{\subparagraph}
  {\itshape}
  {}
  {0em}
  {#1}[ ]
  ```
output:
  pdf_document:
    number_sections: true
    fig_crop: true
    fig_caption: true
    keep_tex: false
---
\newpage
\tableofcontents
\newpage
\pagestyle{fancy}

# Units

- unit chart

|prefix|base 10|base 2|
|--:|:--|:--|
|pico|$10^{-12}$|$2^{-40}$|
|nano|$10^{-9}$|$2^{-30}$|
|micro|$10^{-6}$|$2^{-20}$|
|milli|$10^{-3}$|$2^{-10}$|
|---|$10^0$|$2^{0}$|
|kilo|$10^3$|$2^{10}$|
|mega|$10^6$|$2^{20}$|
|giga|$10^9$|$2^{30}$|
|tera|$10^{12}$|$2^{40}$|
|peta|$10^{15}$|$2^{50}$|

- $Hz \implies \text{cycles per second}$
  - $GHz \implies 10^9 \text{ cycles per second}$
  - etc.

# Formulas

## Frequency
\begin{align*}
f &= \frac{1}{T}&&&&
\end{align*}

## Period
\begin{align*}
T &= \frac{1}{f}&&&&
\end{align*}

## Wavelength
\begin{align*}
\lambda &= vT&&&&\\
\lambda &= \frac{v}{f}&&&&
\end{align*}

## Bandwidth
\begin{align*}
B &= vT&&&&
\end{align*}

## Delay
\begin{align*}
D &= D_P + D_T + D_Q&&&&
\end{align*}

### Propagation
\begin{align*}
D_P &= \frac{\text{distance}}{\text{speed of light}}&&&&
\end{align*}

### Transmit
\begin{align*}
D_T &= \frac{\text{packet size}}{\text{bandwidth}}&&&&
\end{align*}

### Queue
\begin{align*}
D_Q &= \sum_{\text{nodes}}(\text{buffering + switching})&&&&
\end{align*}

### Round Trip Time
\begin{align*}
RTT &= 2D&&&&
\end{align*}

- how long does it take a packet to go **there and back**

## Overhead
\begin{align*}
T_O &= \frac{h}{p} && \text{where $h=$ overhead bits, $p=$ message bits}
\end{align*}

- **extra** over **what we want**

# Error Checking
- VRC
- LRC
- **CRC**
  - this guy is usually used
  - use in tandem with ARQ
- checksum

# ARQ
- automatic repeat request
- handle errors by requesting they be resent
- use in tandem with error detection
  - **CRC**
  - checksum
- main parts
  - **ACKS**
  - **NAKS**
  - **timers**

## Sliding Window
- number frames sequentially
- window of either fixed or variable size
  - see TCP section

### Go Back N
- go back to the beginning of the window and resend everything
- $w - i = N$

### Selective Reject
- **only** resend the **damaged frame**
- need **sorting logic**
  - frames may be out of order

## Stop and Wait
- like sliding window with a **window size $=1$**

# Multiaccess
- problem of **shared channels**
  - who gets a turn?
  - how do we make sure things get to the right place?
- point-to-point is easy (by contrast)

## LANs
- local area network
- shared channel

### Switched LANs
- *interconnection* by *transmission*
- **complex**
  - routing tables
  - hierarchical addressing

### Broadcast LANs
- information *received by all*
- **simple**
  - no routing
  - flat addressing scheme
- MAC (medium access control)
- **used more often**

## Uncoordinated Access Control
- sucks
- $P(\text{exactly one talks}) = np(1-p)^{n-1}$

## MAC Protocol
- Medium Access Control
- **dynamic**
- on demand
- must **minimize** collisions
- two classes
  - random access
  - scheduling

\begin{framed}
\textbf{MAC vs Static}

MAC $\implies$ dynamic, on demand

Static $\implies$ separate dedicated channels
\end{framed}

### Centralized
- *one* **master node**
  - makes decisions for slaves nodes
- *dependent* on **master**
  - what if it fails?
  - less efficient

### Distributed
- all nodes **equivalent**
- make a decision together
  - *distributed* fashion

## How Does MAC Work?
i) **measure** prop time
i) **coordinate** access
i) **select** a winner

### Measure
- ping
- $T_{prop}= \frac{d}{v}$

### Coordinate
\begin{lstlisting}
def coordinateTwoHosts(A,B):
  A.listen(channel)

  if channel not busy:
    A.transmit(m)
    while no message from B:
      A.listen(channel)
    if time > $T_{prop}$:
      break
    else:
      A.retransmit(m)

  repeat for B
\end{lstlisting}

### Select a Winner
- let $T_A =$ time for a collision detected by A
- let $T_B =$ time for a collision detected by B
- A wins $\iff$ $T_A < T_B$
- loser is quiet until winner completes
- winner is quiet after transmission for RTT

## MAC Efficiency
\begin{align*}
E &= \frac{1}{1+2\frac{T_{prop}}{L}} &&&&
\end{align*}

# Ethernet
- **broadcast network**
  - every node can hear every other
- when collision occurs
  - stop sending
  - wait to retransmit

## Limitations
- very large packet size as bandwidth increases
- MAC is technology dependent
  - are measurements accurate?
  - measurements may differ between hosts
- but it is **realistic**
  - uptime is important

## Backoff Protocols
- **queue** of nodes **waiting to transmit**
- keep track of number of attempts
- define $P(x)$
  - probability you transmit on attempt $x$
  - decreasing in $x$

### Implementation
- station $i$ has $bck_i$
- set it to 0
- if queue not empty
  - attempt transmission with $p(bck_i)$
    - fails $\implies bck_i++$
    - succeeds $\implies bck_i := 0$
- if queue was empty, don't change $bck_i$

## Collision-Free Protocols

### Bitmap
- **contention period** = 8 slots
- station $i$ inserts one bit into $i$th slot
- after $N$ slots, each station knows who wants to transmit
- transmit **in order**
- a station $i$ is out of luck if it becomes ready **just after** slot $i$ passes

### Tree Splitting
- nodes are leaves
- recursive
- keep taking left **subtree** until **one node** in **contention**
  - that node wins
  - take right subtree if applicable
  - walk back up to root

### Binary Countdown
- assume **all addresses** are **same length**
- node writes its bit from **highest to lowest order**
  - if I have a 0 and somebody else has a 1
    - I drop out
  - otherwise
    - I stay in
- last man standing wins

# Wireless

## Cellular
- organized into **cells**
  - hexagons
- **neighboring** cells $\implies$ **different frequency bands**

## Ad Hoc
- temporary connection
- **decentralized**
- model with a **Unit Disk Graph**
  - **points** and **circles for range**
  - $G=(V,E)$ where
    - vertices are nodes
    - edges are nodes that can each each other
    - asymmetric ranges $\implies$ directed graph

## Bluetooth

### Formation
- **master nodes**
- **slave nodes**
  - bridge nodes (a special slave)

#### Rules
1. **master** only next to **slaves** (and **bridges**)
1. **slaves** only next to a **master**
1. each master's **piconet** can have **max 7 slaves**
1. bridge between **TWO** masters **ONLY**
